version: '3'

includes:
  default: ./tasks.yaml
  markdownlint: https://raw.githubusercontent.com/vanyda-official/taskfile-markdownlint/main/tasks.yaml
  git: https://raw.githubusercontent.com/vanyda-official/taskfile-git/main/tasks.yaml

dotenv:
  - .env
  - .env.default